import type { Env } from "./types";

/** Pure builder so secret/config forwarding can be verified without a Workers runtime. */
export function portfolioContainerEnvironment(env: Env): Record<string, string> {
  const projectHost = (project: string) =>
    `https://${project}.${env.PORTFOLIO_ENV === "dev" ? "dev." : ""}yousef.codes`;
  const summonBase = projectHost("summon");
  const materiaBase = projectHost("materia");
  const sigilBase = projectHost("sigil");
  const aetherBase = projectHost("aether");
  const seenBase = projectHost("seen");
  const environment: Record<string, string> = {
    PORT: "8080",
    ENVIRONMENT: env.PORTFOLIO_ENV,
    PORTFOLIO_DEBUG_ERRORS: env.PORTFOLIO_ENV === "dev" ? "true" : "false",
    USE_LOCAL_STORE: "false",
    GCP_PROJECT_ID: env.FIRESTORE_PROJECT_ID,
    GOOGLE_CLOUD_PROJECT: env.FIRESTORE_PROJECT_ID,
    FIRESTORE_DATABASE_ID: env.FIRESTORE_DATABASE_ID,
    FIRESTORE_WRITE_MODE: env.FIRESTORE_WRITE_MODE,
    FIRESTORE_SEED_ON_START: "false",
    FIRESTORE_SERVICE_ACCOUNT_JSON_BASE64: env.FIRESTORE_SERVICE_ACCOUNT_JSON_BASE64,
    PORTFOLIO_EDGE_ORIGIN: env.PORTFOLIO_CANONICAL_ORIGIN,
    PORTFOLIO_EDGE_SESSION_BASE_URL: `${env.PORTFOLIO_CANONICAL_ORIGIN}/internal/session`,
    SUMMON_MARKETING_URL: summonBase,
    DOCS_BASE_URL: `${summonBase}/docs`,
    MATERIA_MARKETING_URL: materiaBase,
    MATERIA_DOCS_BASE_URL: `${materiaBase}/docs`,
    SIGIL_MARKETING_URL: sigilBase,
    SIGIL_DOCS_BASE_URL: `${sigilBase}/docs`,
    AETHER_MARKETING_URL: aetherBase,
    AETHER_DOCS_BASE_URL: `${aetherBase}/docs`,
    SEEN_MARKETING_URL: seenBase,
    SEEN_DOCS_BASE_URL: `${seenBase}/docs`,
    EDGE_ORIGIN_TOKEN: env.EDGE_ORIGIN_TOKEN,
    FINOPS_INTERNAL_INGEST_TOKEN: env.FINOPS_INTERNAL_INGEST_TOKEN,
    FINOPS_ALLOCATION_ENTRY_PROJECTIONS_READY: env.FINOPS_ALLOCATION_ENTRY_PROJECTIONS_READY,
    FINOPS_SHARDED_ROLLUP_WRITES_ENABLED: env.FINOPS_SHARDED_ROLLUP_WRITES_ENABLED,
    FINOPS_SHARDED_ROLLUPS_READY: env.FINOPS_SHARDED_ROLLUPS_READY,
    FINOPS_SHARDED_ROLLUP_BACKFILL_EXECUTION_ENABLED: env.FINOPS_SHARDED_ROLLUP_BACKFILL_EXECUTION_ENABLED,
    FINOPS_COVERAGE_START_DATE: env.FINOPS_COVERAGE_START_DATE,
    PORTFOLIO_EDGE_SESSIONS_ENABLED: "true",
    PORTFOLIO_MIGRATION_EXECUTION_ENABLED: env.PORTFOLIO_MIGRATION_EXECUTION_ENABLED,
    PHOTOGRAPHY_MIGRATION_EXECUTION_ENABLED: env.PHOTOGRAPHY_MIGRATION_EXECUTION_ENABLED,
    PHOTOGRAPHY_WRITE_MODE: env.PHOTOGRAPHY_WRITE_MODE,
    PHOTOGRAPHY_UPLOAD_BUCKET: env.PHOTOGRAPHY_UPLOAD_BUCKET,
    PHOTOGRAPHY_UPLOAD_PREFIX: env.PHOTOGRAPHY_UPLOAD_PREFIX,
    PHOTOGRAPHY_MAX_UPLOAD_BYTES: env.PHOTOGRAPHY_MAX_UPLOAD_BYTES,
    PHOTOGRAPHY_R2_BASE_URL: `${env.PORTFOLIO_CANONICAL_ORIGIN}/internal/media`,
    PHOTOGRAPHY_R2_REVERSE_MIRROR: env.PHOTOGRAPHY_R2_REVERSE_MIRROR,
  };
  if (env.FIRESTORE_MIGRATION_PROOF_ID) {
    environment.FIRESTORE_MIGRATION_PROOF_ID = env.FIRESTORE_MIGRATION_PROOF_ID;
  }
  if (env.FINOPS_RECEIPTS) {
    environment.FINOPS_RECEIPT_BASE_URL = `${env.PORTFOLIO_CANONICAL_ORIGIN}/internal/finops`;
  }
  if (env.SAMURAI_FINOPS_IDENTITY_URL && env.FINOPS_IDENTITY_READ_TOKEN) {
    environment.SAMURAI_FINOPS_IDENTITY_URL = env.SAMURAI_FINOPS_IDENTITY_URL;
    environment.FINOPS_IDENTITY_READ_TOKEN = env.FINOPS_IDENTITY_READ_TOKEN;
  }
  return environment;
}
